// src/Export.svelte
<script>
	import { createEventDispatcher } from "svelte";
	import { onMount } from 'svelte';
  import { fade, fly } from "svelte/transition";
  import { data } from "./store.js";
  import fileSaver from "file-saver";
	import tokml from "tokml";
	


	const dispatch = createEventDispatcher();
	let dataGeocoded = null;
	let dataLength  = null;
	let dataGeocodedLength  = null;

	onMount(() => {
		dataLength = $data.length;
		 dataGeocoded = $data.filter(d => d.coords);
		 dataGeocodedLength = dataGeocoded.length;
		console.log('the component has mounted');
	});

  const toGeojson = () => {

    const features = [];

    for (let i = 0; i < dataGeocoded.length; i++) {
      const d = dataGeocoded[i];
      features.push({
        type: "Feature",
        properties: { ...d.input, _score: d.score, _service: d.geocoder },
        geometry: {
          type: "Point",
          coordinates: [d.coords.lng, d.coords.lat]
        }
      });
    }
    return {
      type: "FeatureCollection",
      features: features
    };
  };

  const exportToGeojson = () => {
    const geojson = toGeojson();
    const blob = new Blob([JSON.stringify(geojson)], {
      type: "text/plain;charset=utf-8"
    });
    fileSaver.saveAs(blob, "result_geocode.geojson");
  };

  const exportToKML = () => {
    const geojson = toGeojson();
    const kml = tokml(geojson);
    const blob = new Blob([kml], { type: "text/plain;charset=utf-8" });
    fileSaver.saveAs(blob, "result_geocode.kml");
  };

  const submit = () => {
    dipatch("close");
  };
</script>

<style>
  .modal-background {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.3);
    z-index: 150;
  }

  .modal {
    z-index: 151;
    position: fixed;
    left: 50px;
    top: 50px;
    bottom: 50px;
    right: 50px;
    /* width: calc(100vw - 4em);
	  max-width: 32em;
	  max-height: calc(100vh - 4em); */
    overflow: auto;
    /* transform: translate(-50%, -50%); */
    padding: 0;
    border-radius: 0.2em;
    background: white;
  }

  button {
    display: block;
  }
</style>

<div
  class="modal-background"
  on:click={() => dispatch('close')}
  transition:fade={{ duration: 200 }} />

<div class="modal " transition:fly={{ y: -400, duration: 200 }}>
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Exporter le resultat</span>
    </div>

  </header>

  <button
    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect "
    on:click={() => exportToGeojson()}>
    GeoJson
  </button>

  <button
    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect "
    on:click={() => exportToKML()}>
    KML
  </button>

  <button
    class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect
    mdl-button--accent"
    on:click={() => dispatch('close')}>
    close modal
  </button>
</div>

// src/app/components/export/export.component.ts
import { Component, OnInit, Inject } from '@angular/core';
import { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';
import { GeocoderService } from 'src/app/services/geocoder.service';
import fileSaver from "file-saver";
import tokml from "tokml";

@Component({
  selector: 'app-export',
  templateUrl: './export.component.html',
  styleUrls: ['./export.component.scss']
})
export class ExportComponent implements OnInit {

  dataGeocoded

  constructor(public dialogRef: MatDialogRef<ExportComponent>,
    @Inject(MAT_DIALOG_DATA) public data: any,
    public geocoderService: GeocoderService) { }

  ngOnInit() {
    if (this.geocoderService.data){
      this.dataGeocoded = this.geocoderService.data.filter(d => d.coords)
    }
  }


  toGeojson() {
    const features = [];
    for (let i = 0; i < this.dataGeocoded.length; i++) {
      const d = this.dataGeocoded[i];
      features.push({
        type: "Feature",
        properties: { ...d.input, _score: d.score, _service: d.geocoder },
        geometry: {
          type: "Point",
          coordinates: [d.coords.lng, d.coords.lat]
        }
      });
    }
    return {
      type: "FeatureCollection",
      features: features
    };
  };

 

  exportToGeojson(){
    const geojson = this.toGeojson();
    // // console.log(geojson);
    const blob = new Blob([JSON.stringify(geojson)], {
      type: "text/plain;charset=utf-8"
    });
    let date = new Date().toISOString().split('T')[0]
    fileSaver.saveAs(blob, `Dogeocodeur_${this.dataGeocoded.length}_${date}.geojson`);
  };

  exportToKML() {
    
    const geojson = this.toGeojson();
    const kml = tokml(geojson);
    const blob = new Blob([kml], { type: "text/plain;charset=utf-8" });
    let date = new Date().toISOString().split('T')[0]
    fileSaver.saveAs(blob, `Dogeocodeur_${this.dataGeocoded.length}_${date}.kml`);
  };

  exportToCSV() {
    const header = Object.keys( this.dataGeocoded[0].input );
    header.push('_score','_service', '_lng', '_lat')
    let csvData = []
    csvData.push(header.join(';'))
    const features = [];
    for (let i = 0; i < this.dataGeocoded.length; i++) {
      const d = this.dataGeocoded[i];
      let currentRow = []
      for (let key in d.input){
        currentRow.push(d.input[key].replace('"','""') )
      }
      currentRow.push(d._score, d.geocoder, d.coords.lng, d.coords.lat );
      csvData.push(currentRow.join(';'))
    }
    const csv = csvData.join('\r')

    const blob = new Blob([csv], { type: "text/plain;charset=utf-8" });
    let date = new Date().toISOString().split('T')[0]
    fileSaver.saveAs(blob, `Dogeocodeur_${this.dataGeocoded.length}_${date}.csv`);
  };

}


<mat-toolbar color="primary">
        <mat-toolbar-row>
          <span>Exporter les résultats</span>
          <span class="spacer"></span>
          <mat-icon  class="pointer" (click)="dialogRef.close()">close</mat-icon>
        </mat-toolbar-row>
      
      </mat-toolbar>



<div class="content">
    <div>
            Nombre de points à exporter : <b>{{this.dataGeocoded ? this.dataGeocoded.length || 0 : 0}}</b>
    </div>
        

        <div class="divExportButton">
        <button [disabled]="!this.dataGeocoded" class="exportButton" mat-raised-button color="primary" (click)="exportToGeojson()"> Geojson </button>
        
        <button [disabled]="!this.dataGeocoded" class="exportButton" mat-raised-button color="primary" (click)="exportToKML()"> KML </button>
        <button [disabled]="!this.dataGeocoded" class="exportButton" mat-raised-button color="primary" (click)="exportToCSV()"> CSV </button>
    </div>
    
</div>
